### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by Scellow** [tlgkccampbell/ultraviolet#29]
I was wondering why the CPU usage was that high

So i tested using sample project from here and same result, CPU usage is really high when the window is in front

Window in Front: (60 FPS -> 30% CPU)
![2016-04-23_11-11-41](https://cloud.githubusercontent.com/assets/4980894/14760449/ca744de8-0944-11e6-982b-b2fea06a594b.png)

Window in Inactive: (48 FPS -> <1% CPU)
![devenv_2016-04-23_11-15-43](https://cloud.githubusercontent.com/assets/4980894/14760450/cdeb4bd4-0944-11e6-88e3-76dbdb5a68d1.png)

Code: https://gist.github.com/Scellow/c7664c1cbf1ef6fd5089245c0de3de88

**Comment by tlgkccampbell** [comment]
Are you using the release assemblies, or are you building Ultraviolet yourself? When built in the Debug configuration, Ultraviolet deliberately introduces a number of pipeline stalls in order to ensure correctness and provide better error messages (mostly through calls to `glGet()` and `glError()`).

Also, try putting the following into your `OnInitialized()` method:

    Ultraviolet.Host.IsFixedTimeStep = false;
    Ultraviolet.GetPlatform().Windows.GetPrimary().SynchronizeWithVerticalRetrace = true;

It looks like my defaults for these might differ from MonoGame's, and it also looks like there may potentially be an issue in my catch-up code when `IsFixedTimeStep` is set to `true`, so I'm going to look into addressing those issues in 1.3.8.

**Comment by RUSshy** [comment]
Your code solved my issue thanks !

I'm using the ones from the installer

**Comment by Scellow** [comment]
Your code solved my issue thanks !

I'm using the ones from the installer

**Comment by tlgkccampbell** [comment]
I've just pushed some code to the `develop` branch which should:

 1. Make `SynchronizeWithVerticalRetrace` default to `true`, and
 2. Improve CPU usage when `IsFixedTimeStep` is `true`

These changes will be a part of the 1.3.8 release.
