### ISSUE TITLE
Feature Request: Filewatcher

### ISSUE THREAD

**Issue by RUSshy** [tlgkccampbell/ultraviolet#48]
Hello

It would be cool to implement something like filewatcher, so if asset is changed, it is automatically reloaded

For example:

Change in UI SCREEN XML, the UI is reloaded to display the new one, without restarting the game, same for sprites

I found i waste to much time to restart the game just to see a small change for the UI

Ty!

**Comment by tlgkccampbell** [comment]
This would be somewhat difficult to solve in the general case. There's nothing stopping you from doing something like:

```csharp
private Texture2D texture;

// ...

texture = content.Load<Texture2D>("mytexture");
```

In that case, reloading the content file isn't going to do you any good, because you've got a copy of the old one stashed away. It could maybe be implemented as something that you have to specifically request for certain assets:

```csharp
private WatchedAsset<Texture2D> texture;

// ...

texture = content.LoadWatched<Texture2D>("mytexture");
```

...but that would require you to specifically handle that asset being reloaded at runtime.

This is further complicated by the fact that, during development, you have two copies of every asset: the copy in your solution, and the copy that's put in the `Debug` or `Release` folder when the solution is compiled. The application loads the latter, while you probably want to stick to editing the former. This can probably be worked around, but it needs to be considered.

I do agree with you, though, that it would be nice to be able to reload UPF views without having to restart the application. I'll put it on the list of things to think about for the next major version.

**Comment by tlgkccampbell** [comment]
I'll be merging the feature branch containing this functionality into the dev branch for 1.3.15 once everything works its way through my CI server, so it'll be part of the next release (which should be out soon-ish, barring any major unforeseen issues).
