### ISSUE TITLE
12% CPU for 18 buttons

### ISSUE THREAD

**Issue by RUSshy** [tlgkccampbell/ultraviolet#68]
Hi, i noticed high CPU usage for my UI, so i checked simple view, and buttons seems to have lot of overhead, i dont know what wrong, but check this simple code, it use lot of CPU

https://pastebin.com/rPdggqqx

https://pasteboard.co/GZYNdVy.png

**Comment by tlgkccampbell** [comment]
You're probably not doing anything wrong. The Presentation Foundation is a bit performance intensive due to the way that the dependency object system works, so if you have large, deeply nested control trees you might see your CPU usage start to climb upward.

That said, I'm always looking for more ways to optimize things, so with any luck this will improve as time goes on.

**Comment by RUSshy** [comment]
It is way better with the .net core version, "only" 7-8% cpu now

**Comment by tlgkccampbell** [comment]
I would be interested in knowing if you see a similar change when using the .NET Framework 4.7 libraries built from the most recent source; I made some changes to how dependency objects work in a recent commit that may be responsible.
