### ISSUE TITLE
Consider unlisting deprecated packages on NuGet

### ISSUE THREAD

**Issue by orthoxerox** [tlgkccampbell/ultraviolet#83]
I've noticed that you've marked the older versions of the packages as deprecated. Consider [unlisting](https://docs.microsoft.com/en-us/vsts/package/nuget/unlist-delete?view=vsts) them, so they are not visible in the gallery. They will still be available for projects that reference them.

**Comment by tlgkccampbell** [comment]
I don't think this functionality was available when I deprecated those packages. I wonder when it was added.

I'm going through them and unlisting them all now. I really wish nuget.org didn't require you to do this one version at a time. 😭

**Comment by tlgkccampbell** [comment]
Further research leads me to believe that this functionality did exist, I was just blind. Oops.

At any rate, I went through and delisted all of the deprecated packages. They're still showing up in the search for me but I assume that's just because it takes time for the index to be updated. 

Thanks for the tip!
